name: Lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - uses: 0918nobita/setup-cljstyle@v1.0.0-alpha.1
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.PAT }}
        with:
          cljstyle-version: "0.15.0"
          run-check: |
            reviewdog-enabled: true
